
export const CREATE_OBJECION = 'CREATE_OBJECION'
export const DELETE_OBJECION = 'DELETE_OBJECION'
export const FETCH_ALL_OBJECIONES = 'FETCH_ALL_OBJECIONES'
export const UPDATE_OBJECION = 'UPDATE_OBJECION'