
export const CREATE_OBJECION = 'CREATE_OBJECION'
export const DELETE_OBJECION = 'DELETE_OBJECION'
export const FETCH_ALL_OBJECIONES = 'FETCH_ALL_OBJECIONES'
export const UPDATE_OBJECION = 'UPDATE_OBJECION'

export const CREATE_SUGERENCIA = 'CREATE_SUGERENCIA'
export const DELETE_SUGERENCIA = 'DELETE_SUGERENCIA'
export const FETCH_ALL_SUGERENCIAS = 'FETCH_ALL_SUGERENCIAS'
export const UPDATE_SUGERENCIA = 'UPDATE_SUGERENCIA'